config/routes.rb
Rails.application.routes.draw do

  # Necessary for the pagination in will_paginate
  scope path: Railspress.posts_permalink_prefix do
    get 'page/:page' => 'railspress/home#posts'
    get 'tag/:slug/page/:page' => 'railspress/archive#taxonomy', defaults: { taxonomy: 'post_tag' }
    get 'author/:slug/page/:page' => 'railspress/archive#author', defaults: { taxonomy: 'author' }, as: :authors_posts
    get ':taxonomy/:slug/page/:page' => 'railspress/archive#taxonomy'
  end

  scope :admin do
    resources :options, controller: 'railspress/options', as: :admin_options
  end

  get 'test' => 'railspress/home#testing_page'

  # get '*slug' => 'railspress/posts#singular', as: :show_page

  mount Railspress::Engine => '/'

  # scope :news do
  #   # get ':slug' => 'railspress/posts#singular'
  #   get 'tag/:slug' => 'railspress/archive#taxonomy', defaults: {taxonomy: 'post_tag'}
  #   get ':taxonomy/:slug' => 'railspress/archive#taxonomy'
  # end

  root 'railspress/home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'railspress/twentynineteen/index_application'

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_breadcrumb(breadcrumb)
    unless breadcrumb.nil?
      unless breadcrumb.blank?
        breadcrumb[breadcrumb.keys.last] = nil
      end
      content_tag :nav, 'aria-label': 'breadcrumb' do
        content_tag :ol, class: 'breadcrumb' do
          breadcrumb.each do |text, path|
            if path.nil?
              concat content_tag :li, text, class: 'breadcrumb-item active'
            elsif path.is_a? Hash
              concat content_tag :li, link_to(text, path[:url]), class: 'breadcrumb-item', title: path[:title]
            else
              concat content_tag :li, link_to(text, path), class: 'breadcrumb-item'
            end
          end
        end
      end
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark mb-0 pt-md-0 sticky">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd">
        <path d="M15.246 17c-.927 3.701-2.547 6-3.246 7-.699-1-2.32-3.298-3.246-7h6.492zm7.664 0c-1.558 3.391-4.65 5.933-8.386 6.733 1.315-2.068 2.242-4.362 2.777-6.733h5.609zm-21.82 0h5.609c.539 2.386 1.47 4.678 2.777 6.733-3.736-.8-6.828-3.342-8.386-6.733zm14.55-2h-7.28c-.29-1.985-.29-4.014 0-6h7.281c.288 1.986.288 4.015-.001 6zm-9.299 0h-5.962c-.248-.958-.379-1.964-.379-3s.131-2.041.379-3h5.962c-.263 1.988-.263 4.012 0 6zm17.28 0h-5.963c.265-1.988.265-4.012.001-6h5.962c.247.959.379 1.964.379 3s-.132 2.042-.379 3zm-8.375-8h-6.492c.925-3.702 2.546-6 3.246-7 1.194 1.708 2.444 3.799 3.246 7zm-8.548-.001h-5.609c1.559-3.39 4.651-5.932 8.387-6.733-1.237 1.94-2.214 4.237-2.778 6.733zm16.212 0h-5.609c-.557-2.462-1.513-4.75-2.778-6.733 3.736.801 6.829 3.343 8.387 6.733z"/>
      </svg>
    <% end %>
    <% nav_menu_args = {menu_class: 'navbar-nav',
                        container: 'div',
                        container_class: 'collapse navbar-collapse',
                        container_id: 'navbarCollapse',
                        walker: Railspress::BootstrapNavwalker.new,
                        fallback_cb: 'Railspress::BootstrapNavwalker.fallback'
    }
       nav_menu_args[:theme_location] = 'menu-1'
    %>
    <%= wp_nav_menu(nav_menu_args) %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dummy theme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel='stylesheet' id='wp-block-library-css'  href='<%= includes_url('css/dist/block-library/style.min.css') %>' type='text/css' media='all' />
    <link rel='stylesheet' id='wp-block-library-theme-css'  href='<%= includes_url('css/dist/block-library/theme.min.css') %>' type='text/css' media='all' />
    <%= javascript_include_tag 'application' %>
  </head>

  <body <%= body_class.html_safe %>>
<div id="page" class="site">

  <%= render 'layouts/header' %>

  <%= bootstrap_flash %>

  <div id="content" class="site-content">
    <section id="primary" class="content-area">
      <main id="main" class="site-main">
        <%= display_breadcrumb @breadcrumb %>
        <%= yield %>
      </main>
    </section>
  </div>

  <footer class="site-footer">
    <div class="site-info">
      <% blog_info = get_bloginfo('name') %>
      <% unless blog_info.blank? %>
        <%= link_to bloginfo('name'), esc_url(home_url('/')), class: 'site-name', rel: 'home' %>,
      <% end %>
    </div>
  </footer>

</div>
  </body>
</html>

app/views/railspress/archive/category-website.html.erb
<% if !@posts.empty? %>
  <%= content_tag :header, class: 'page-header' do %>
    <%= the_archive_title( '<h1 class="page-title" style="color:#0073aa">', '</h1>' ) %>
    <%= "The other category:" %>
    <%= link_to "Uncategorized", railspress_engine.category_posts_path(slug: 'uncategorized') %>
  <% end %>
  <% @posts.each do |post| %>
    <%= render partial: 'railspress/posts/content_excerpt', locals: {post: post} %>
  <% end %>
<% else %>
  <%= render partial: 'railspress/posts/content_none' %>
<% end %>

<%= content_tag :nav, class: 'navigation pagination', role: 'navigation' do %>
  <%= will_paginate @posts, class: 'nav-links', previous_label: t('railspress.post.index.newer'), next_label: t('railspress.post.index.older') %>
<% end %>

app/views/railspress/posts/_entry_header.html.erb
<%= content_tag :header, class: 'entry-header' do %>
  <%= content_tag :h2, post.post_title, class: 'entry-title' %>
<% end %>

app/views/shortcode_templates/ts_childpages.html.erb
<%
  # normalize attribute keys, lowercase
  ts_atts = @attributes.transform_keys!(&:downcase)
  # override default attributes with user attributes
  ts_atts = {sort_column: 'menu_order', sort_order: 'asc', no_content: false }.merge(ts_atts)
  childpages = get_children({post_parent: @attributes[:page].id, post_type: 'page', post_status: 'publish', orderby: ts_atts[:sort_column], order: ts_atts[:sort_order].to_sym}).values
%>

<%= @content %>

<% unless childpages.empty? %>
  <%= content_tag :div, childpages.each.map {|copil| output_page_as_card(copil, ts_atts[:no_content] == 'true')}.join.html_safe, class: 'row'  %>
<% end %>

app/views/shortcode_templates/ts_revisions.html.erb
<%= @content %>